In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn import preprocessing, svm, model_selection as ms
from sklearn.pipeline import Pipeline

%matplotlib inline

In [2]:
df = pd.read_csv('C:\\Users\\Nick\\Desktop\\SAB python\\dataset_MathAvg.csv')

In [3]:
df.head()

,School,student key,student_academic_year,Math EOY Average,student_Class,student_section,Nationality,Gender,Age at begining of year/monthes,year in School,...,Science Homework Term1Wk3,Science Homework Term1Wk4,Science Homework Term1Wk5,Science Homework Term1Wk6,Science Homework Term1Wk7,Science Homework Term1Wk8,Science Homework Term1Wk9,Science Homework Term1Wk10,Science Homework Term1Wk11,Science Homework Term1Wk12
0,Abu Dhabi,3159,1112,66.459345,8,B,Australia,M,158,5,...,68.75,NaN,75.000000,NaN,51.5625,NaN,55.319149,NaN,36.363636,NaN
1,Abu Dhabi,3216,1112,59.725652,8,A,Italy,M,160,5,...,81.25,NaN,94.444444,NaN,67.1875,NaN,23.404255,NaN,59.090909,NaN
2,Abu Dhabi,3310,1112,54.929375,8,E,United Arab Emirates,M,169,5,...,75.00,NaN,59.722222,NaN,59.3750,NaN,42.553191,NaN,22.727273,NaN
3,Abu Dhabi,3317,1112,76.593686,8,C,United Arab Emirates,M,167,5,...,75.00,NaN,86.111111,NaN,67.1875,NaN,63.829787,NaN,29.545455,NaN
4,Abu Dhabi,3632,1112,66.742820,8,B,United Arab Emirates,F,157,5,...,62.50,NaN,56.944444,NaN,56.2500,NaN,63.829787,NaN,54.545455,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16493 entries, 0 to 16492
Columns: 108 entries, School to Science Homework Term1Wk12
dtypes: float64(88), int64(13), object(7)
memory usage: 13.6+ MB

In [5]:
df.corr()

,student key,student_academic_year,Math EOY Average,student_Class,Age at begining of year/monthes,year in School,Math Teacher weekly infraction avg,English Teacher weekly infraction avg,Science Teacher weekly infraction avg,Term 1 Periodic 1 Math Average,...,Science Homework Term1Wk3,Science Homework Term1Wk4,Science Homework Term1Wk5,Science Homework Term1Wk6,Science Homework Term1Wk7,Science Homework Term1Wk8,Science Homework Term1Wk9,Science Homework Term1Wk10,Science Homework Term1Wk11,Science Homework Term1Wk12
student key,1.000000,0.157110,0.162805,-0.034608,-0.071470,-0.368059,-0.121449,-0.291209,-0.240015,0.138728,...,0.146241,0.104130,0.176724,0.112259,0.196949,0.133844,0.110944,0.135162,0.110435,0.080699
student_academic_year,0.157110,1.000000,-0.030143,-0.000022,-0.027300,0.271198,0.123084,0.112329,-0.017402,0.033618,...,0.121933,-0.088124,0.000846,-0.225470,0.052068,0.050073,0.139885,0.069415,0.131654,-0.052211
Math EOY Average,0.162805,-0.030143,1.000000,-0.063693,-0.104173,-0.092425,-0.139131,-0.125403,-0.088641,0.617212,...,0.489264,0.475636,0.564960,0.617708,0.589468,0.384813,0.469653,0.554632,0.512181,0.596854
student_Class,-0.034608,-0.000022,-0.063693,1.000000,0.825137,0.109148,-0.016949,0.048120,0.005306,0.095313,...,0.102396,-0.003725,0.016169,-0.146682,-0.161624,-0.097188,-0.242420,-0.220589,-0.238505,-0.129094
Age at begining of year/monthes,-0.071470,-0.027300,-0.104173,0.825137,1.000000,-0.015297,-0.041760,0.062041,0.003035,0.041595,...,-0.012028,-0.051111,-0.084305,-0.117045,-0.197675,-0.114130,-0.214424,-0.187077,-0.211628,-0.091726
year in School,-0.368059,0.271198,-0.092425,0.109148,-0.015297,1.000000,0.010182,-0.007862,-0.035404,-0.021273,...,-0.053754,-0.068159,-0.077422,-0.140966,-0.046444,-0.039609,-0.038009,-0.049239,-0.064679,-0.127933
Math Teacher weekly infraction avg,-0.121449,0.123084,-0.139131,-0.016949,-0.041760,0.010182,1.000000,0.443887,0.403168,-0.066611,...,-0.073005,-0.068139,-0.109559,-0.159545,-0.117717,-0.065039,0.005555,-0.068212,-0.032342,-0.115659
English Teacher weekly infraction avg,-0.291209,0.112329,-0.125403,0.048120,0.062041,-0.007862,0.443887,1.000000,0.417665,-0.061745,...,-0.083388,-0.106106,-0.109620,-0.173244,-0.132868,-0.075766,-0.013936,-0.059676,0.006425,-0.027706
Science Teacher weekly infraction avg,-0.240015,-0.017402,-0.088641,0.005306,0.003035,-0.035404,0.403168,0.417665,1.000000,-0.027102,...,-0.085973,-0.094236,-0.158720,-0.072019,-0.145155,-0.160683,-0.090259,-0.165805,-0.026753,-0.174390
Term 1 Periodic 1 Math Average,0.138728,0.033618,0.617212,0.095313,0.041595,-0.021273,-0.066611,-0.061745,-0.027102,1.000000,...,0.383543,0.436582,0.515223,0.422236,0.435574,0.424275,0.342780,0.401909,0.420890,0.418404
Term 1 Periodic 2 Math Average,0.135745,0.043729,0.686658,-0.099083,-0.118429,-0.040564,-0.068250,-0.094676,-0.099114,0.545292,...,0.408632,0.479672,0.519546,0.510196,0.445732,0.414042,0.477868,0.403534,0.524333,0.504286
Term 1 Periodic 3 Math Average,0.162824,-0.027788,0.692460,-0.238236,-0.243684,-0.064730,-0.140960,-0.153164,-0.106582,0.500026,...,0.412824,0.439589,0.530006,0.604673,0.467158,0.442298,0.402846,0.424692,0.430732,0.524059
Term 1 Periodic 4 Math Average,0.131273,-0.030673,0.694295,-0.214818,-0.215537,-0.063779,-0.100644,-0.120060,-0.076603,0.501353,...,0.380331,0.515359,0.491440,0.600857,0.481982,0.488384,0.482906,0.450209,0.539483,0.516126
Term 1 Periodic 5 Math Average,0.143547,-0.152969,0.665852,-0.086877,-0.105786,-0.095856,-0.130165,-0.183273,-0.174622,0.458717,...,0.338414,0.563067,0.438947,0.546331,0.442234,0.226692,0.474393,0.521289,0.384245,0.280837
Term 1 Periodic 6 Math Average,0.135336,-0.050757,0.703490,-0.008007,-0.053665,-0.086651,-0.024314,-0.019994,-0.008476,0.441311,...,0.383237,0.629191,0.517897,0.630806,0.451491,0.646609,0.595119,0.670783,0.481102,0.187352
Term 1 Periodic 7 Math Average,0.027995,-0.230252,0.590922,0.060673,-0.036384,-0.033429,0.218763,0.159824,0.270962,0.416669,...,0.562717,0.532717,0.603533,0.546239,0.527167,0.284265,-0.382836,0.536420,0.373408,0.026079
Term 1 Periodic 8 Math Average,0.077398,-0.005959,0.785432,0.005858,-0.082063,0.004101,0.066047,0.087159,0.207338,-0.400526,...,0.993905,NaN,1.000000,0.030405,NaN,NaN,-1.000000,-0.055215,NaN,0.389766
Term 1 Final Math Average,0.160078,-0.070915,0.852036,-0.092640,-0.126408,-0.091268,-0.117443,-0.120141,-0.060201,0.550067,...,0.382213,0.409233,0.514239,0.585758,0.571933,0.325536,0.433892,0.453378,0.550742,0.521070
Term 1 Periodic 1 English Average,0.167564,0.112337,0.495514,-0.300971,-0.305032,-0.027785,0.054541,-0.073393,-0.051274,0.433197,...,0.407635,0.390519,0.527170,0.370890,0.524546,0.468173,0.510214,0.307272,0.385007,0.467849
Term 1 Periodic 2 English Average,0.184158,0.032988,0.440174,-0.235638,-0.231530,-0.072473,-0.003477,-0.031891,-0.017275,0.397417,...,0.543896,0.359412,0.494683,0.297335,0.371589,0.392077,0.532197,0.327698,0.490830,0.444057
Term 1 Periodic 3 English Average,0.136419,0.227613,0.553110,-0.123238,-0.128603,-0.029391,-0.038429,-0.146114,-0.077275,0.362051,...,0.575278,0.570875,0.558060,0.510807,0.507030,0.574531,0.492186,0.535017,0.487544,0.537553
Term 1 Periodic 4 English Average,0.154417,0.404761,0.515787,-0.175961,-0.181617,-0.061023,0.018089,-0.133573,-0.025514,0.435258,...,0.531287,NaN,0.510598,0.606384,NaN,0.620058,NaN,0.617413,0.661338,0.569488
Term 1 Periodic 5 English Average,0.051831,-0.055464,0.514845,-0.132346,0.079009,0.064613,0.011983,0.040272,-0.101352,0.574314,...,0.548137,0.743780,0.565122,0.547018,0.459231,NaN,0.476915,0.501911,NaN,NaN
Term 1 Periodic 6 English Average,0.223012,-0.058303,0.328819,0.021844,-0.073922,0.025930,-0.055993,-0.250984,-0.116616,0.211972,...,0.253658,0.214833,0.362050,0.103127,0.414991,0.288392,0.382802,0.276847,0.191288,0.073354
Term 1 Periodic 7 English Average,-0.003261,-0.257078,0.379942,0.082617,-0.030207,-0.019271,0.061760,0.140567,0.176067,0.352283,...,0.264971,0.453334,0.404712,0.275424,0.349636,0.261106,0.355403,0.226638,0.464867,0.218099
Term 1 Periodic 8 English Average,0.225052,0.015731,0.663170,0.090635,0.013082,-0.055143,-0.046491,-0.109218,-0.087634,0.546754,...,0.590924,0.458971,0.666712,0.499202,0.569224,0.443487,0.577146,0.470751,0.576697,0.580608
Term 1 Final English Average,0.185531,0.015683,0.665844,-0.167696,-0.201256,-0.072768,-0.025099,-0.108182,-0.072585,0.517327,...,0.498724,0.387143,0.592844,0.465937,0.562352,0.334469,0.517975,0.455817,0.617876,0.528531
Term 1 Periodic 1 Science Average,0.194793,0.098253,0.622556,-0.255410,-0.268798,-0.047953,-0.048375,-0.067778,-0.110622,0.414061,...,0.644991,0.626213,0.703547,0.688443,0.597903,0.418005,0.617980,0.483814,0.642090,0.546724
Term 1 Periodic 2 Science Average,0.191454,0.262083,0.573034,-0.243895,-0.259981,0.014429,-0.048199,-0.053265,-0.136804,0.331217,...,0.389406,0.475030,0.569275,0.518923,0.712165,0.633567,0.734908,0.613718,0.615406,0.553229
Term 1 Periodic 3 Science Average,0.204253,0.095680,0.746201,-0.096363,-0.152027,0.025166,-0.207366,-0.221595,-0.133240,0.540310,...,0.535601,0.649807,0.647582,0.726267,0.706231,0.713195,0.731645,0.701240,0.688101,0.672202
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Science AMS Term1Wk7,0.110330,0.014874,0.450118,-0.077695,-0.086066,-0.095191,-0.079821,-0.054325,-0.128179,0.318603,...,0.521871,0.689621,0.471009,0.599279,0.675282,0.750381,0.508863,0.648650,0.502828,0.648211
Science AMS Term1Wk8,0.102767,0.065554,0.353176,-0.078763,-0.094717,-0.064350,-0.045104,-0.043631,-0.112683,0.331830,...,0.533489,0.693961,0.573148,0.564535,0.644814,0.762413,0.591278,0.682415,0.527496,0.574242
Science AMS Term1Wk9,0.079365,0.062329,0.370122,-0.257496,-0.242746,-0.096062,-0.034690,-0.038866,-0.065217,0.274015,...,0.550886,0.679282,0.546253,0.634435,0.661208,0.669377,0.710915,0.587230,0.574032,0.687101
Science AMS Term1Wk10,0.106211,0.104382,0.384086,-0.128372,-0.133891,-0.059404,-0.051018,-0.040602,-0.109649,0.264478,...,0.370235,0.573218,0.366933,0.547326,0.548755,0.663560,0.564395,0.736365,0.475711,0.736621
Science AMS Term1Wk11,0.099533,0.021549,0.478324,0.040883,0.008430,-0.085039,-0.044895,-0.055291,-0.098742,0.358091,...,0.479593,0.623371,0.516800,0.578025,0.645306,0.599821,0.529891,0.665921,0.677027,0.757787
Science AMS Term1Wk12,0.130857,-0.029369,0.444496,0.037521,-0.004030,-0.082252,-0.081262,0.001375,-0.118356,0.270725,...,0.449259,0.752995,0.417354,0.640585,0.602302,0.596812,0.534055,0.706127,0.622212,0.766918
Math Homework Term1Wk1,0.144523,0.176675,0.546103,-0.120618,-0.176071,-0.034391,-0.215978,-0.303108,-0.181492,0.462951,...,0.445858,0.534670,0.436942,0.507265,0.407445,0.509416,0.428765,0.535203,0.391202,0.584248
Math Homework Term1Wk2,0.067303,0.071347,0.368192,0.062974,0.018489,-0.080576,-0.020407,-0.026854,-0.057756,0.419504,...,0.542990,0.659003,0.485527,0.585410,0.393270,0.596801,0.544994,0.477247,0.434314,0.410354
Math Homework Term1Wk3,0.090787,-0.124518,0.447924,0.245187,0.146102,-0.125733,-0.064852,-0.072253,-0.051852,0.577005,...,0.507947,0.656581,0.510567,0.591165,0.413923,0.522395,0.410367,0.433305,0.372081,0.415464
Math Homework Term1Wk4,0.100547,-0.143334,0.505833,-0.028451,-0.044155,-0.145580,-0.069088,-0.071678,-0.068238,0.449403,...,0.420054,0.607290,0.474193,0.618178,0.488249,0.576145,0.410913,0.526754,0.370496,0.560783
Math Homework Term1Wk5,0.107834,-0.014511,0.552894,-0.042709,-0.058871,-0.096219,-0.146302,-0.131165,-0.095986,0.442976,...,0.428396,0.641391,0.498844,0.675624,0.445905,0.463875,0.452265,0.494989,0.452370,0.535125
Math Homework Term1Wk6,0.110546,-0.014836,0.501004,-0.038518,-0.063311,-0.097015,-0.054197,-0.069381,-0.062708,0.439382,...,0.413269,0.637173,0.433829,0.662569,0.352907,0.502274,0.387899,0.564003,0.417221,0.520532
Math Homework Term1Wk7,0.099438,-0.181775,0.452667,-0.094652,-0.106953,-0.155592,-0.070327,-0.124855,-0.063319,0.364634,...,0.387548,0.588785,0.434304,0.644329,0.552235,0.601673,0.479774,0.592920,0.404336,0.495675
Math Homework Term1Wk8,0.113422,-0.048561,0.568251,0.009691,-0.042272,-0.122311,-0.087650,-0.089303,-0.101310,0.426229,...,0.418237,0.579031,0.457569,0.640230,0.518811,0.518645,0.458418,0.571343,0.430089,0.554893
Math Homework Term1Wk9,0.107982,0.035877,0.551214,0.066513,-0.000266,-0.074151,-0.055337,-0.071535,-0.057275,0.466872,...,0.412047,0.549442,0.419918,0.552590,0.495482,0.537383,0.434902,0.568660,0.458690,0.623725
Math Homework Term1Wk10,0.122957,-0.053587,0.597550,-0.098233,-0.120934,-0.117466,-0.088412,-0.072794,-0.058459,0.412066,...,0.390621,0.483698,0.418312,0.532967,0.509855,0.478973,0.443657,0.499086,0.541467,0.625317
Math Homework Term1Wk11,0.162322,0.024888,0.640604,-0.210260,-0.186105,-0.115788,-0.134203,-0.104133,-0.127765,0.380973,...,0.392026,0.518364,0.427481,0.560087,0.583956,0.497187,0.487379,0.650535,0.634733,0.653325
Math Homework Term1Wk12,0.152261,0.102630,0.604567,-0.237155,-0.234884,-0.106072,-0.039977,-0.033207,-0.065477,0.326961,...,0.455158,0.744329,0.457868,0.643767,0.620385,0.657102,0.604606,0.680034,0.575041,0.689180
Science Homework Term1Wk1,0.116827,NaN,0.348717,NaN,-0.025736,-0.096955,0.055310,0.092170,0.034496,0.171374,...,0.326739,NaN,0.327810,NaN,NaN,0.265448,NaN,0.319653,NaN,NaN
Science Homework Term1Wk2,0.042205,-0.085088,0.332360,0.035798,0.011166,-0.104167,-0.076509,-0.042672,-0.029573,0.365417,...,0.974136,0.755708,0.959114,0.607375,0.531881,0.762956,0.628228,0.566011,0.217679,0.692714
Science Homework Term1Wk3,0.146241,0.121933,0.489264,0.102396,-0.012028,-0.053754,-0.073005,-0.083388,-0.085973,0.383543,...,1.000000,0.899243,0.664085,0.681873,0.391258,0.830323,0.565890,0.539142,0.589489,0.500546
Science Homework Term1Wk4,0.104130,-0.088124,0.475636,-0.003725,-0.051111,-0.068159,-0.068139,-0.106106,-0.094236,0.436582,...,0.899243,1.000000,0.968283,0.729224,0.706287,0.725303,0.721161,0.655185,0.245304,0.687254
Science Homework Term1Wk5,0.176724,0.000846,0.564960,0.016169,-0.084305,-0.077422,-0.109559,-0.109620,-0.158720,0.515223,...,0.664085,0.968283,1.000000,0.890414,0.648484,0.868229,0.699993,0.547851,0.630620,0.586993
Science Homework Term1Wk6,0.112259,-0.225470,0.617708,-0.146682,-0.117045,-0.140966,-0.159545,-0.173244,-0.072019,0.422236,...,0.681873,0.729224,0.890414,1.000000,0.673429,0.473710,0.720516,0.569895,0.611525,0.586693
Science Homework Term1Wk7,0.196949,0.052068,0.589468,-0.161624,-0.197675,-0.046444,-0.117717,-0.132868,-0.145155,0.435574,...,0.391258,0.706287,0.648484,0.673429,1.000000,0.709437,0.700697,0.598487,0.635401,0.509747
Science Homework Term1Wk8,0.133844,0.050073,0.384813,-0.097188,-0.114130,-0.039609,-0.065039,-0.075766,-0.160683,0.424275,...,0.830323,0.725303,0.868229,0.473710,0.709437,1.000000,0.974942,0.741771,0.757373,0.624645
Science Homework Term1Wk9,0.110944,0.139885,0.469653,-0.242420,-0.214424,-0.038009,0.005555,-0.013936,-0.090259,0.342780,...,0.565890,0.721161,0.699993,0.720516,0.700697,0.974942,1.000000,0.811281,0.735786,0.679695
Science Homework Term1Wk10,0.135162,0.069415,0.554632,-0.220589,-0.187077,-0.049239,-0.068212,-0.059676,-0.165805,0.401909,...,0.539142,0.655185,0.547851,0.569895,0.598487,0.741771,0.811281,1.000000,0.792687,0.799326
Science Homework Term1Wk11,0.110435,0.131654,0.512181,-0.238505,-0.211628,-0.064679,-0.032342,0.006425,-0.026753,0.420890,...,0.589489,0.245304,0.630620,0.611525,0.635401,0.757373,0.735786,0.792687,1.000000,0.695398
Science Homework Term1Wk12,0.080699,-0.052211,0.596854,-0.129094,-0.091726,-0.127933,-0.115659,-0.027706,-0.174390,0.418404,...,0.500546,0.687254,0.586993,0.586693,0.509747,0.624645,0.679695,0.799326,0.695398,1.000000

In [6]:
pd.set_option('display.max_columns', None)

In [17]:
df.describe()

,student key,student_academic_year,Math EOY Average,student_Class,Age at begining of year/monthes,year in School,Math Teacher weekly infraction avg,English Teacher weekly infraction avg,Science Teacher weekly infraction avg,Term 1 Periodic 1 Math Average,Term 1 Periodic 2 Math Average,Term 1 Periodic 3 Math Average,Term 1 Periodic 4 Math Average,Term 1 Periodic 5 Math Average,Term 1 Periodic 6 Math Average,Term 1 Periodic 7 Math Average,Term 1 Periodic 8 Math Average,Term 1 Final Math Average,Term 1 Periodic 1 English Average,Term 1 Periodic 2 English Average,Term 1 Periodic 3 English Average,Term 1 Periodic 4 English Average,Term 1 Periodic 5 English Average,Term 1 Periodic 6 English Average,Term 1 Periodic 7 English Average,Term 1 Periodic 8 English Average,Term 1 Final English Average,Term 1 Periodic 1 Science Average,Term 1 Periodic 2 Science Average,Term 1 Periodic 3 Science Average,Term 1 Periodic 4 Science Average,Term 1 Periodic 5 Science Average,Term 1 Periodic 6 Science Average,Term 1 Periodic 7 Science Average,Term 1 Periodic 8 Science Average,Term 1 Final Science Average,Term 1 AMS Math Average,Term 1 HW Math Average,Term 1 Math Average,Term 1 English Average,Term 1 AMS English Average,Term 1 HW English Average,Term 1 AMS Science Average,Term 1 HW Science Average,Term 1 Science Average,Term 1 Total Average,Missing Exams Term 1 Math,Missing Exams Term 1 English,Missing Exams Term 1 Science,Term 1 # days absent,Term 1 # infractions,Term 1 Extra Curricular points,Math AMS Term1Wk1,Math AMS Term1Wk2,Math AMS Term1Wk3,Math AMS Term1Wk4,Math AMS Term1Wk5,Math AMS Term1Wk6,Math AMS Term1Wk7,Math AMS Term1Wk8,Math AMS Term1Wk9,Math AMS Term1Wk10,Math AMS Term1Wk11,Math AMS Term1Wk12,Math AMS Term2Wk1,Science AMS Term1Wk1,Science AMS Term1Wk2,Science AMS Term1Wk3,Science AMS Term1Wk4,Science AMS Term1Wk5,Science AMS Term1Wk6,Science AMS Term1Wk7,Science AMS Term1Wk8,Science AMS Term1Wk9,Science AMS Term1Wk10,Science AMS Term1Wk11,Science AMS Term1Wk12,Math Homework Term1Wk1,Math Homework Term1Wk2,Math Homework Term1Wk3,Math Homework Term1Wk4,Math Homework Term1Wk5,Math Homework Term1Wk6,Math Homework Term1Wk7,Math Homework Term1Wk8,Math Homework Term1Wk9,Math Homework Term1Wk10,Math Homework Term1Wk11,Math Homework Term1Wk12,Science Homework Term1Wk1,Science Homework Term1Wk2,Science Homework Term1Wk3,Science Homework Term1Wk4,Science Homework Term1Wk5,Science Homework Term1Wk6,Science Homework Term1Wk7,Science Homework Term1Wk8,Science Homework Term1Wk9,Science Homework Term1Wk10,Science Homework Term1Wk11,Science Homework Term1Wk12,AvgMathPeriodic,AvgEnglishPeriodic,AvgSciencePeriodic,AvgMathAMS,AvgScienceAMS,AvgMathHW,AvgScienceHW
count,16493.000000,16493.000000,16493.000000,16493.000000,16493.000000,16493.000000,16493.000000,16493.000000,16493.000000,14923.000000,15444.000000,13065.000000,11233.000000,8202.000000,2082.000000,702.000000,203.000000,16325.000000,15779.000000,10597.000000,5163.000000,1215.000000,297.000000,1695.000000,1245.000000,16330.000000,16361.000000,15720.000000,15648.000000,2669.000000,3.000000,2.000000,101.000000,699.000000,833.000000,15564.000000,16368.000000,10387.000000,16371.000000,16371.000000,0.0,10386.000000,11176.000000,10386.000000,16368.000000,16378.000000,16493.000000,16493.000000,16493.000000,16493.000000,16493.000000,9743.000000,2889.000000,13835.000000,15488.000000,14216.000000,15324.000000,14666.000000,13768.000000,14775.000000,14036.000000,15559.000000,14568.000000,10465.000000,12420.000000,166.000000,3687.000000,9279.000000,8052.000000,10033.000000,9199.000000,9838.000000,10931.000000,10576.000000,10622.000000,9971.000000,7196.000000,1624.000000,8413.000000,9717.000000,7933.000000,9704.000000,9527.000000,7003.000000,8710.000000,9650.000000,10025.000000,6031.000000,4100.000000,175.000000,2838.000000,5434.000000,3829.000000,5229.000000,4642.000000,3672.000000,4040.000000,5330.000000,5045.000000,3329.000000,1870.000000,16320.000000,16336.000000,16312.000000,16367.000000,11175.000000,10386.000000,10385.000000
mean,5549.952525,1328.029649,82.265102,6.912448,140.746741,4.820894,10.201116,14.044019,8.807919,80.037992,79.090192,81.819160,81.752657,81.926460,80.737674,73.745513,86.606158,81.314237,79.207829,82.421204,77.436405,78.759483,80.598463,75.186832,75.438299,81.138936,81.127069,80.158195,80.519132,80.552930,92.000000,93.480000,69.190594,87.621989,84.953181,81.634558,87.304553,77.379430,81.806017,81.768541,NaN,80.072120,84.665373,78.080190,81.733637,82.234116,0.625659,0.646699,0.218881,1.720791,7.042200,32.791748,116.114185,92.564542,91.832181,90.373999,87.653651,87.797011,88.504702,88.008514,87.908684,85.507586,84.631225,81.565493,88.375727,73.734940,84.516081,88.128288,88.476487,86.823762,84.429019,84.738432,88.273672,86.530178,84.802487,78.780056,82.972972,77.518687,78.687648,80.467361,79.502108,78.712253,79.199493,78.007317,76.297115,74.275007,75.977880,77.739628,79.756214,74.944361,78.736963,79.791033,81.884888,79.630431,70.772435,81.833662,77.427930,84.606023,71.475654,78.388386,75.957693,80.515297,79.706081,80.511733,88.416769,85.363709,77.820211,78.453377
std,4082.428696,142.433926,11.905707,0.810568,11.909553,2.332542,7.748494,9.965609,8.539018,15.776166,16.824165,16.181332,16.772731,16.323476,16.428495,20.043189,13.145499,14.677709,12.693403,13.478316,17.935656,16.984982,10.012247,13.463051,11.999556,12.938859,11.797314,17.429581,18.369993,18.004585,7.566373,9.220672,19.914710,14.071459,16.195488,16.216026,10.461990,13.462433,12.176121,10.342257,NaN,13.569245,12.557400,15.436056,14.191607,10.353606,1.488268,1.461245,0.702454,2.888619,8.356711,38.999869,86.660888,17.892581,18.102934,18.231386,19.413596,19.645637,16.867339,17.471902,18.655250,18.957008,17.331758,17.828341,15.409254,18.517424,24.347572,25.107974,25.300953,25.400307,23.348437,20.437645,21.998107,23.054419,23.640489,23.245452,21.181945,19.608708,21.172680,20.116704,21.749187,20.702521,21.869132,22.988949,21.240325,23.588620,23.560036,23.245419,24.879616,63.551378,34.892579,17.589511,24.500793,18.990239,25.764504,16.687954,30.631466,18.006526,23.332942,21.156186,21.982728,13.256386,11.666603,16.021695,16.232933,20.611023,18.191075,19.883898
min,6.000000,1112.000000,13.939181,6.000000,107.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.180000,4.110000,35.000000,4.070000,0.000000,0.000000,0.000000,10.000000,50.000000,0.000000,0.000000,23.344705,22.527272,0.000000,0.000000,0.000000,83.500000,86.960000,15.230000,13.640000,5.380000,0.000000,13.793103,21.525998,21.370725,30.302124,NaN,18.040142,17.381228,8.204209,7.045530,29.403274,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.666667,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.125000,0.000000,0.000000,0.000000,9.677419,4.000000,20.000000,9.090909,8.333333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,10.526316,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.851852,0.000000,12.006667,24.130795,0.000000,13.793103,17.381229,21.525999,8.204210
25%,2049.000000,1213.000000,74.331131,6.000000,131.000000,3.000000,5.000000,7.000000,3.000000,70.845000,68.750000,72.420000,73.180000,72.970000,70.962500,60.000000,80.000000,72.525000,71.988967,75.000000,67.500000,69.320000,74.360000,66.670000,70.000000,73.924390,74.759090,70.400000,71.110000,71.430000,89.000000,90.220000,58.330000,83.330000,80.110000,72.740000,81.591222,68.838734,74.090625,75.665603,NaN,72.340599,77.523284,68.568546,73.308472,75.625697,0.000000,0.000000,0.000000,0.000000,1.000000,9.000000,86.666667,89.404481,88.000000,85.454545,81.666667,81.600000,82.727273,82.087114,81.818182,77.931034,76.666667,71.111111,83.404255,60.333333,77.272727,81.026316,81.333333,79.130435,75.555556,76.130952,81.666667,77.894737,75.200000,67.340067,74.444444,66.000000,69.767442,71.590909,69.230769,68.354430,68.115942,66.965149,65.336538,61.165049,63.461538,65.116279,69.191489,50.000000,66.666667,69.444444,71.621622,70.238095,54.274510,72.972973,65.957447,77.500000,57.575758,66.666667,65.853659,72.402500,72.743494,71.358750,81.833662,77.546422,68.830705,68.621033
50%,4984.000000,1314.000000,84.493969,7.000000,140.000000,5.000000,8.000000,12.000000,6.000000,83.330000,82.690000,85.980000,86.110000,85.860000,85.000000,77.500000,90.000000,84.960000,81.631250,85.500666,81.666666,83.670000,82.050000,75.960000,76.000000,84.147058,83.825454,84.780000,85.940000,86.110000,94.500000,93.480000,71.260000,91.930000,90.860000,86.290000,90.276597,79.409765,84.157657,83.705517,NaN,82.891479,87.851071,81.388888,85.268025,83.945660,0.000000,0.000000,0.000000,1.000000,4.000000,20.000000,94.670000,96.000000,95.294118,94.400000,92.500000,92.258065,92.500000,92.413793,92.727273,90.666667,89.230769,86.060606,93.333333,77.333333,88.000000,92.857143,92.941176,91.764706,88.888889,89.677419,93.000000,91.000000,90.000000,83.809524,88.888889,80.232558,81.720430,84.210526,83.146067,82.352941,82.608696,81.333333,78.481013,76.287939,79.746835,81.818182,85.555556,78.947368,82.857143,84.782609,86.486486,84.000000,74.129249,85.714286,83.333333,88.888889,75.757576,81.818182,80.487805,82.948333,81.889773,84.532500,90.480487,87.871148,79.486730,81.422222
75%,7921.000000,1415.000000,91.986963,8.000000,150.000000,7.000000,13.000000,18.000000,12.000000,92.280000,92.380000,95.000000,94.870000,94.950000,94.440000,90.000000,97.500000,93.048571,89.037500,92.500000,91.665000,91.666666,88.460000,85.000000,83.790000,91.222547,90.000000,93.840000,95.450000,94.130000,96.250000,96.740000,84.200000,96.670000,95.560000,94.450000,95.452382,87.779778,91.572167,89.793324,NaN,90.693589,94.707142,90.389024,93.058095,90.493615,1.000000,1.000000,0.000000,2.000000,10.000000,42.000000,100.000000,100.000000,98.545455,98.461538,97.966102,97.500000,97.333333,97.333333,98.000000,96.946387,96.428571,95.384615,98.260870,88.000000,94.666667,100.000000,100.000000,98.279570,96.923077,97.142857,98.333333,98.000000,97.500000,94.117647,96.363636,91.071429,90.322581,93.243243,93.258427,92.053848,92.592593,91.891892,90.076923,90.476190,92.000000,94.346667,95.238095,94.736842,93.750000,93.750000,94.915254,92.857143,90.215826,94.285714,94.122257,95.744681,88.235294,92.857143,90.243902,90.952333,88.722566,93.345000,95.744266,94.738926,87.839339,90.426587
max,22476.000000,1516.000000,100.000000,8.000000,193.000000,9.000000,40.000000,53.000000,65.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,98.750000,100.000000,97.750000,102.018181,100.000000,100.000000,100.000000,100.000000,98.000000,100.000000,98.560000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,NaN,100.000000,100.000000,100.000000,100.000000,100.000000,33.000000,44.000000,20.000000,68.000000,83.000000,636.000000,454.545455,625.000000,555.555556,500.000000,515.210526,625.000000,480.000000,458.047619,500.000000,530.888889,402.791667,370.370370,482.000000,100.000000,648.866667,769.230769,666.666667,769.230769,714.285714,648.866667,693.857143,710.076923,666.666667,666.666667,526.315789,168.000000,586.714286,493.827161,492.519480,533.333333,769.230769,603.228070,677.966102,778.638298,907.047619,670.000000,547.945205,831.052632,941.789474,100.000000,558.278932,636.076923,588.928151,236.742857,1152.296296,657.435897,552.147971,680.000000,410.878661,100.000000,100.000000,100.000000,447.386658,669.871795,670.000000,696.332185

In [8]:
df.isnull().mean().sort_values(ascending=False)

Term 1 AMS English Average               1.000000
Term 1 Periodic 5 Science Average        0.999879
Term 1 Periodic 4 Science Average        0.999818
Term 1 Periodic 6 Science Average        0.993876
Science AMS Term1Wk1                     0.989935
Science Homework Term1Wk1                0.989389
Term 1 Periodic 8 Math Average           0.987692
Term 1 Periodic 5 English Average        0.981992
Term 1 Periodic 7 Science Average        0.957618
Term 1 Periodic 7 Math Average           0.957436
Term 1 Periodic 8 Science Average        0.949494
Term 1 Periodic 4 English Average        0.926332
Term 1 Periodic 7 English Average        0.924513
Math Homework Term1Wk1                   0.901534
Term 1 Periodic 6 English Average        0.897229
Science Homework Term1Wk12               0.886619
Term 1 Periodic 6 Math Average           0.873765
Term 1 Periodic 3 Science Average        0.838174
Science Homework Term1Wk2                0.827927
Math AMS Term1Wk1                        0.824835
Science Homework Term1Wk11               0.798157
Science Homework Term1Wk7                0.777360
Science AMS Term1Wk2                     0.776451
Science Homework Term1Wk4                0.767841
Science Homework Term1Wk8                0.755048
Math Homework Term1Wk12                  0.751410
Science Homework Term1Wk6                0.718547
Science Homework Term1Wk10               0.694113
Term 1 Periodic 3 English Average        0.686958
Science Homework Term1Wk5                0.682956
                                           ...
Term 1 Periodic 1 English Average        0.043291
Term 1 Final Math Average                0.010186
Term 1 Periodic 8 English Average        0.009883
Term 1 Final English Average             0.008003
Term 1 Science Average                   0.007579
Term 1 AMS Math Average                  0.007579
Term 1 English Average                   0.007397
Term 1 Math Average                      0.007397
Term 1 Total Average                     0.006973
Math Teacher                             0.000000
student key                              0.000000
student_academic_year                    0.000000
Math EOY Average                         0.000000
student_Class                            0.000000
student_section                          0.000000
Nationality                              0.000000
Gender                                   0.000000
Age at begining of year/monthes          0.000000
year in School                           0.000000
Missing Exams Term 1 Math                0.000000
Math Teacher weekly infraction avg       0.000000
English Teacher                          0.000000
English Teacher weekly infraction avg    0.000000
Science Teacher                          0.000000
Science Teacher weekly infraction avg    0.000000
Missing Exams Term 1 English             0.000000
Missing Exams Term 1 Science             0.000000
Term 1 # days absent                     0.000000
Term 1 # infractions                     0.000000
School                                   0.000000
Length: 108, dtype: float64

In [9]:
colsmath = [
    'Term 1 Periodic 1 Math Average',
    'Term 1 Periodic 2 Math Average',
    'Term 1 Periodic 3 Math Average',
    'Term 1 Periodic 4 Math Average',
    'Term 1 Periodic 5 Math Average',
    'Term 1 Periodic 6 Math Average',
    'Term 1 Periodic 7 Math Average',
    'Term 1 Periodic 8 Math Average'
]

df['AvgMathPeriodic']= df[colsmath].mean(axis=1)

In [10]:
colsenglish = [
    'Term 1 Periodic 1 English Average',
    'Term 1 Periodic 2 English Average',
    'Term 1 Periodic 3 English Average',
    'Term 1 Periodic 4 English Average',
    'Term 1 Periodic 5 English Average',
    'Term 1 Periodic 6 English Average',
    'Term 1 Periodic 7 English Average',
    'Term 1 Periodic 8 English Average'
]

df['AvgEnglishPeriodic']= df[colsenglish].mean(axis=1)

In [11]:
colsscience = [
    'Term 1 Periodic 1 Science Average',
    'Term 1 Periodic 2 Science Average',
    'Term 1 Periodic 3 Science Average',
    'Term 1 Periodic 4 Science Average',
    'Term 1 Periodic 5 Science Average',
    'Term 1 Periodic 6 Science Average',
    'Term 1 Periodic 7 Science Average',
    'Term 1 Periodic 8 Science Average'
]

df['AvgSciencePeriodic']= df[colsscience].mean(axis=1)

In [12]:
colsmathams = [
    'Math AMS Term1Wk1',
    'Math AMS Term1Wk2',
    'Math AMS Term1Wk3',
    'Math AMS Term1Wk4',
    'Math AMS Term1Wk5',
    'Math AMS Term1Wk6',
    'Math AMS Term1Wk7',
    'Math AMS Term1Wk8',
    'Math AMS Term1Wk9',
    'Math AMS Term1Wk10',
    'Math AMS Term1Wk11',
    'Math AMS Term1Wk12'
]

df['AvgMathAMS']= df[colsmathams].mean(axis=1)

colsscienceams = [
    'Science AMS Term1Wk1',
    'Science AMS Term1Wk2',
    'Science AMS Term1Wk3',
    'Science AMS Term1Wk4',
    'Science AMS Term1Wk5',
    'Science AMS Term1Wk6',
    'Science AMS Term1Wk7',
    'Science AMS Term1Wk8',
    'Science AMS Term1Wk9',
    'Science AMS Term1Wk10',
    'Science AMS Term1Wk11',
    'Science AMS Term1Wk12'
]

df['AvgScienceAMS']= df[colsscienceams].mean(axis=1)

colsmathhw = [
    'Math Homework Term1Wk1',
    'Math Homework Term1Wk2',
    'Math Homework Term1Wk3',
    'Math Homework Term1Wk4',
    'Math Homework Term1Wk5',
    'Math Homework Term1Wk6',
    'Math Homework Term1Wk7',
    'Math Homework Term1Wk8',
    'Math Homework Term1Wk9',
    'Math Homework Term1Wk10',
    'Math Homework Term1Wk11',
    'Math Homework Term1Wk12'
]

df['AvgMathHW']= df[colsmathhw].mean(axis=1)

colssciencehw = [
    'Science Homework Term1Wk1',
    'Science Homework Term1Wk2',
    'Science Homework Term1Wk3',
    'Science Homework Term1Wk4',
    'Science Homework Term1Wk5',
    'Science Homework Term1Wk6',
    'Science Homework Term1Wk7',
    'Science Homework Term1Wk8',
    'Science Homework Term1Wk9',
    'Science Homework Term1Wk10',
    'Science Homework Term1Wk11',
    'Science Homework Term1Wk12'
]

df['AvgScienceHW']= df[colssciencehw].mean(axis=1)

In [19]:
df.head()

,School,student key,student_academic_year,Math EOY Average,student_Class,student_section,Nationality,Gender,Age at begining of year/monthes,year in School,Math Teacher,Math Teacher weekly infraction avg,English Teacher,English Teacher weekly infraction avg,Science Teacher,Science Teacher weekly infraction avg,Term 1 Periodic 1 Math Average,Term 1 Periodic 2 Math Average,Term 1 Periodic 3 Math Average,Term 1 Periodic 4 Math Average,Term 1 Periodic 5 Math Average,Term 1 Periodic 6 Math Average,Term 1 Periodic 7 Math Average,Term 1 Periodic 8 Math Average,Term 1 Final Math Average,Term 1 Periodic 1 English Average,Term 1 Periodic 2 English Average,Term 1 Periodic 3 English Average,Term 1 Periodic 4 English Average,Term 1 Periodic 5 English Average,Term 1 Periodic 6 English Average,Term 1 Periodic 7 English Average,Term 1 Periodic 8 English Average,Term 1 Final English Average,Term 1 Periodic 1 Science Average,Term 1 Periodic 2 Science Average,Term 1 Periodic 3 Science Average,Term 1 Periodic 4 Science Average,Term 1 Periodic 5 Science Average,Term 1 Periodic 6 Science Average,Term 1 Periodic 7 Science Average,Term 1 Periodic 8 Science Average,Term 1 Final Science Average,Term 1 AMS Math Average,Term 1 HW Math Average,Term 1 Math Average,Term 1 English Average,Term 1 AMS English Average,Term 1 HW English Average,Term 1 AMS Science Average,Term 1 HW Science Average,Term 1 Science Average,Term 1 Total Average,Missing Exams Term 1 Math,Missing Exams Term 1 English,Missing Exams Term 1 Science,Term 1 # days absent,Term 1 # infractions,Term 1 Extra Curricular points,Math AMS Term1Wk1,Math AMS Term1Wk2,Math AMS Term1Wk3,Math AMS Term1Wk4,Math AMS Term1Wk5,Math AMS Term1Wk6,Math AMS Term1Wk7,Math AMS Term1Wk8,Math AMS Term1Wk9,Math AMS Term1Wk10,Math AMS Term1Wk11,Math AMS Term1Wk12,Math AMS Term2Wk1,Science AMS Term1Wk1,Science AMS Term1Wk2,Science AMS Term1Wk3,Science AMS Term1Wk4,Science AMS Term1Wk5,Science AMS Term1Wk6,Science AMS Term1Wk7,Science AMS Term1Wk8,Science AMS Term1Wk9,Science AMS Term1Wk10,Science AMS Term1Wk11,Science AMS Term1Wk12,Math Homework Term1Wk1,Math Homework Term1Wk2,Math Homework Term1Wk3,Math Homework Term1Wk4,Math Homework Term1Wk5,Math Homework Term1Wk6,Math Homework Term1Wk7,Math Homework Term1Wk8,Math Homework Term1Wk9,Math Homework Term1Wk10,Math Homework Term1Wk11,Math Homework Term1Wk12,Science Homework Term1Wk1,Science Homework Term1Wk2,Science Homework Term1Wk3,Science Homework Term1Wk4,Science Homework Term1Wk5,Science Homework Term1Wk6,Science Homework Term1Wk7,Science Homework Term1Wk8,Science Homework Term1Wk9,Science Homework Term1Wk10,Science Homework Term1Wk11,Science Homework Term1Wk12,AvgMathPeriodic,AvgEnglishPeriodic,AvgSciencePeriodic,AvgMathAMS,AvgScienceAMS,AvgMathHW,AvgScienceHW
0,Abu Dhabi,3159,1112,66.459345,8,B,Australia,M,158,5,MMH1,13,ELB2,10,PCD1,4,86.0,87.860,95.33,NaN,NaN,NaN,NaN,NaN,69.665,70.125,NaN,60.0,NaN,NaN,NaN,NaN,80.063529,66.780000,47.06,66.95,49.25,NaN,NaN,NaN,NaN,NaN,53.0,60.339020,71.908195,73.624103,66.146894,NaN,51.449848,71.542887,57.399056,58.198841,64.913242,4,1,0,11,6,NaN,NaN,NaN,NaN,6.25,98.333333,14.285714,88.333333,94.594595,65.833333,14.814815,82.424242,78.181818,NaN,NaN,NaN,NaN,54.545455,72.571429,84.324324,83.225806,86.206897,76.153846,70.000000,72.413793,44.444444,NaN,NaN,87.5,81.081081,64.705882,100.000000,77.777778,57.333333,55.789474,68.269231,54.716981,NaN,NaN,NaN,68.75,NaN,75.000000,NaN,51.5625,NaN,55.319149,NaN,36.363636,NaN,89.730000,70.062843,54.420000,60.339020,71.542888,71.908196,57.399057
1,Abu Dhabi,3216,1112,59.725652,8,A,Italy,M,160,5,MSS1,7,ESD1,5,SRT1,3,85.0,NaN,66.13,NaN,NaN,NaN,NaN,NaN,50.800,75.835,NaN,NaN,NaN,NaN,NaN,NaN,92.202352,83.026470,58.47,NaN,53.13,NaN,NaN,NaN,NaN,NaN,49.0,74.431409,65.022008,66.847784,85.142781,NaN,85.753855,70.688820,65.075421,59.226619,73.915159,4,2,1,5,15,10.0,NaN,NaN,NaN,100.00,83.333333,89.142857,75.833333,89.729730,57.500000,42.222222,65.454545,66.666667,NaN,NaN,NaN,NaN,60.606061,71.428571,64.864865,77.419355,83.448276,66.153846,58.000000,77.241379,77.037037,NaN,NaN,87.5,68.918919,82.352941,80.000000,56.666667,70.666667,40.000000,51.923077,47.169811,NaN,NaN,NaN,81.25,NaN,94.444444,NaN,67.1875,NaN,23.404255,NaN,59.090909,NaN,75.565000,84.018676,55.800000,74.431410,70.688821,65.022009,65.075422
2,Abu Dhabi,3310,1112,54.929375,8,E,United Arab Emirates,M,169,5,MSS1,7,EJP1,6,AH,2,81.5,66.625,71.96,NaN,NaN,NaN,NaN,NaN,61.005,64.165,NaN,65.5,NaN,NaN,NaN,NaN,65.058235,58.127272,44.47,57.72,16.00,NaN,NaN,NaN,NaN,NaN,55.0,48.230544,51.378751,59.428797,61.566052,NaN,61.704208,49.920153,51.875537,48.912915,63.522341,0,0,0,1,3,NaN,NaN,NaN,NaN,81.25,12.500000,37.142857,41.666667,87.567568,62.500000,29.629630,24.242424,57.575758,NaN,NaN,NaN,NaN,33.333333,48.571429,29.729730,51.612903,74.482759,61.538462,53.333333,44.827586,51.851852,NaN,NaN,87.5,68.918919,58.823529,48.421053,30.000000,62.666667,52.631579,32.692308,20.754717,NaN,NaN,NaN,75.00,NaN,59.722222,NaN,59.3750,NaN,42.553191,NaN,22.727273,NaN,73.361667,64.907745,39.396667,48.230545,49.920154,51.378752,51.875537
3,Abu Dhabi,3317,1112,76.593686,8,C,United Arab Emirates,M,167,5,MMK1,8,EKM1,15,AH,2,80.0,68.850,85.98,NaN,NaN,NaN,NaN,NaN,71.250,81.780,NaN,52.0,NaN,NaN,NaN,NaN,79.484705,77.111363,64.00,64.25,82.44,NaN,NaN,NaN,NaN,NaN,61.0,81.699670,76.195447,75.648796,78.018851,NaN,76.226314,64.952316,64.334770,65.165156,73.369279,0,0,0,1,14,NaN,NaN,NaN,NaN,100.00,93.333333,90.857143,83.333333,88.648649,93.333333,51.851852,51.515152,82.424242,NaN,NaN,NaN,NaN,39.393939,86.857143,27.027027,92.258065,89.655172,65.384615,76.000000,82.068966,25.925926,NaN,NaN,95.0,82.432432,94.117647,80.000000,86.666667,76.000000,70.526316,53.846154,47.169811,NaN,NaN,NaN,75.00,NaN,86.111111,NaN,67.1875,NaN,63.829787,NaN,29.545455,NaN,78.276667,71.088235,70.230000,81.699671,64.952317,76.195447,64.334771
4,Abu Dhabi,3632,1112,66.742820,8,B,United Arab Emirates,F,157,5,MMH1,13,ELB2,10,PCD1,4,72.0,55.380,85.98,NaN,NaN,NaN,NaN,NaN,72.915,52.265,NaN,47.5,NaN,NaN,NaN,NaN,71.206470,53.222727,39.00,37.29,55.06,NaN,NaN,NaN,NaN,NaN,58.5,79.274565,73.290514,72.859042,70.495924,NaN,70.810515,62.456708,58.813937,55.321826,64.306444,2,7,0,2,12,NaN,NaN,NaN,NaN,97.50,74.166667,81.142857,65.833333,86.486486,90.833333,76.296296,70.303030,70.909091,NaN,NaN,NaN,NaN,67.878788,49.142857,59.459459,62.580645,71.724138,67.692308,48.000000,68.965517,66.666667,NaN,NaN,87.5,83.783784,41.176471,100.000000,66.666667,81.333333,69.473684,73.076923,56.603774,NaN,NaN,NaN,62.50,NaN,56.944444,NaN,56.2500,NaN,63.829787,NaN,54.545455,NaN,71.120000,56.990490,43.783333,79.274566,62.456709,73.290515,58.813937

In [ ]:
mapper = DataFrameMapper([
    ('student_Class', None),
    ('Math EOY Average', None),
    ('Term 1 Final Math Average', None),
    ('Term 1 Final English Average', None),
    ('Term 1 Final Science Average', None),
    ('Age at begining of year/monthes', None),
    ('year in School', None),
    ('Math Teacher weekly infraction avg', None),
    ('Missing Exams Term 1 Math', None),
    ('Missing Exams Term 1 English', None),
    ('Missing Exams Term 1 Science', None),
    ('Term 1 # days absent', None),
    ('Term 1 # infractions', None),
    ('Term 1 Extra Curricular points', None),
    ('AvgMathPeriodic', None),
    ('AvgEnglishPeriodic', None),
    ('AvgSciencePeriodic', None),
    ('AvgMathAMS', None),
    ('AvgScienceAMS', None),
    ('AvgMathHW', None),
    ('AvgScienceHW', None),
    ('School', ce.OneHotEncoder()),
    ('Nationality', ce.OneHotEncoder()),
    ('Math Teacher', ce.OneHotEncoder()),
])